spring:
  thymeleaf:
    # 开启thymeleaf视图解析
    enabled: true
    # 模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    # 编码 可不用配置
    encoding: UTF-8
    # 内容类别,可不用配置
    content-type: text/html
    # 开发配置为false,避免修改模板还要重启服务器
    cache: false
    # 配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/
    # 后缀名
    suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.196.190.46:3306/my_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: Jianghs@123

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: false
