server:
  port: 8080
spring:
  profiles:
    include: repository
  thymeleaf:
    # 开启thymeleaf视图解析
    enabled: true
    # 模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML
    # 编码 可不用配置
    encoding: UTF-8
    # 内容类别,可不用配置
    content-type: text/html
    # 开发配置为false,避免修改模板还要重启服务器
    cache: false
    # 配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/
    # 后缀名
    suffix: .html
